[workspace]
members = [
    "crates/common/icn-types",
    "crates/common/icn-crypto",
    "crates/common/icn-identity-core",
    "tests/codec_tests"
]
resolver = "2"

[workspace.metadata.dev-dependencies]
cargo-deny = { version = "^0.14", default-features = false }

[[test]]
name = "codec_verification"
path = "tests/codec_verification.rs"
