site_name: InterCooperative Network (ICN)
site_description: Documentation for the ICN project
repo_url: https://github.com/example/icn-v3
docs_dir: docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Architecture:
    - DAG Store: dag_store.md
    - Mesh Execution: mesh_execution.md
    - Governance Lifecycle: governance_lifecycle.md
  - APIs:
    - AgoraNet API: agoranet_api.md

plugins:
  - search 