# Cooperative Configuration Template
# ---------------------------------
# This template provides the necessary configuration for an ICN v3 Cooperative.
# Cooperatives are economic engines within the ICN, managing production, trade, 
# and token issuance.

cooperative:
  # Basic Cooperative Information
  id: "coop-test-cooperative"  # Required: Unique identifier for this cooperative
  name: "Test Cooperative"  # Required: Human-readable cooperative name
  description: "A test cooperative for testing"  # Optional: Cooperative description
  
  # Federation Membership
  federation:
    id: "fed-test-federation"  # Required: Federation this cooperative belongs to
    
  # Cooperative Governance Parameters
  governance:
    quorum_type: "MAJORITY"  # Options: MAJORITY, THRESHOLD, WEIGHTED
    threshold: 3  # Only used when quorum_type is THRESHOLD
    weights: {}  # Only used when quorum_type is WEIGHTED
    voting_period_seconds: 86400  # Default: 1 day (24 hours)
    
  # Cooperative Administration
  admins:
    # List of DIDs authorized as cooperative operators
    operator_dids:
      - "did:key:did:icn:mock:fedadmin30125"
      - "did:key:did:icn:mock:fedadmin5664"
      - "did:key:did:icn:mock:fedadmin21810"
  
  # Cooperative Economic Parameters
  economic:
    # Token configuration
    token:
      symbol: "TCOOP"
      name: "Test Cooperative Token"
      decimals: 6
      initial_supply: 1000000  # Initial token supply (if applicable)
      transferable: true
      
    # Minting policy
    minting:
      authorized_minters:
        - "did:key:did:icn:mock:fedadmin30125"
        - "did:key:did:icn:mock:fedadmin5664"
      max_mint_per_tx: 1000000
      requires_quorum: true  # Whether minting requires quorum approval
    
    # Transfer policy
    transfers:
      permit_external: true  # Allow transfers to other cooperatives
      external_federations:  # List of federations where transfers are allowed
        - "fed-${EXTERNAL_FEDERATION_ID}"
  
  # Cooperative Storage Configuration
  storage:
    data_path: "/home/matt/dev/icn-v3/onboarding_test/data/cooperative/test-cooperative"
    token_ledger:
      type: "inmemory"  # Options: inmemory, rocksdb, postgres
      # Only used when type is postgres
      postgres:
        host: "${POSTGRES_HOST}"
        port: 5432
        user: "${POSTGRES_USER}"
        password: "${POSTGRES_PASSWORD}"
        database: "${POSTGRES_DATABASE}"
        table_prefix: "coop_test-cooperative_"
  
  # Cooperative Monitoring Configuration
  monitoring:
    metrics_prefix: "coop_test-cooperative"
    logging:
      level: "info"  # Options: debug, info, warn, error
      file_path: "/home/matt/dev/icn-v3/onboarding_test/logs/cooperative_test-cooperative.log"
      
  # Resource Limits
  resources:
    max_communities: 50
    max_token_transactions_per_day: 100000
    
  # Default Community Template
  templates:
    community: "/home/matt/dev/icn-v3/onboarding_test/data/cooperative/test-cooperative/templates/community_template.yaml" 