[package]
name = "icn-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_cbor = "0.11"
thiserror = "1.0"
cid = { version = "0.10", features = ["serde"] }

[dev-dependencies]
serde_test = "1"
