version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: icn_ledger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  icn-agoranet:
    build:
      context: ../../..
      dockerfile: crates/services/icn-agoranet/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/icn_ledger
      - USE_POSTGRES=true
      - RUST_LOG=icn_agoranet=debug,tower_http=debug
    ports:
      - "8787:8787"
    restart: unless-stopped

volumes:
  pgdata: 