[package]
name = "icn-identity-core"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "1.0"
base64 = "0.21"
multibase = "0.9"
thiserror = "1.0"

[dev-dependencies]
assert_matches = "1.5"
rand = "0.7" 